DROP SEQUENCE HIBERNATE_SEQUENCE;

DROP TABLE kunde CASCADE CONSTRAINTS PURGE;
DROP TABLE adresse CASCADE CONSTRAINTS PURGE;
DROP TABLE bestellung CASCADE CONSTRAINTS PURGE;
DROP TABLE artikel CASCADE CONSTRAINTS PURGE;
DROP TABLE bestellposition CASCADE CONSTRAINTS PURGE;
DROP TABLE lieferung CASCADE CONSTRAINTS PURGE;
DROP TABLE bestellung_lieferung CASCADE CONSTRAINTS PURGE;
DROP TABLE artikelgruppe CASCADE CONSTRAINTS PURGE;
